// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  aboutSidebar: [{ type: "autogenerated", dirName: "about" }],
  archSidebar: [{ type: "autogenerated", dirName: "architecture" }],
  apiSidebar: [{ type: "autogenerated", dirName: "api" }],

  aptosSidebar: [{ type: "autogenerated", dirName: "aptos" }],
  coreSidebar: [{ type: "autogenerated", dirName: "core" }],
  nearSidebar: [{ type: "autogenerated", dirName: "near" }],
  solanaSidebar: [{ type: "autogenerated", dirName: "solana" }],
  starknetSidebar: [{ type: "autogenerated", dirName: "starknet" }],
  suiSidebar: [{ type: "autogenerated", dirName: "sui" }],
};

module.exports = sidebars;
