// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  gettingStartedSidebar: [
    { type: "autogenerated", dirName: "getting-started" },
  ],
  archSidebar: [{ type: "autogenerated", dirName: "architecture" }],
  apiSidebar: [{ type: "autogenerated", dirName: "api" }],

  aptosSidebar: [{ type: "autogenerated", dirName: "aptos" }],
  coreDaoSidebar: [{ type: "autogenerated", dirName: "coredao" }],
  nearSidebar: [{ type: "autogenerated", dirName: "near" }],
  solanaSidebar: [{ type: "autogenerated", dirName: "solana" }],
  starknetSidebar: [{ type: "autogenerated", dirName: "starknet" }],
  suiSidebar: [{ type: "autogenerated", dirName: "sui" }],
};

module.exports = sidebars;
