// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  gettingStartedSidebar: [
    "about",
    "oracles",
    "network",
    "faq",
    "terminology",
    { type: "html", value: '<hr class="sidebar-separator">' },
    {
      type: "category",
      label: "Products",
      link: {
        type: "doc",
        id: "products",
      },
      collapsible: false,
      items: [{ type: "autogenerated", dirName: "products" }],
    },
    { type: "html", value: '<hr class="sidebar-separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">Architecture</h3>',
    },
    { type: "autogenerated", dirName: "arch" },
  ],

  guidesSidebar: [
    "guides/overview",
    { type: "html", value: '<hr class="sidebar-separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">Solana</h3>',
    },
    { type: "ref", id: "solana/guides/feeds" },
    { type: "ref", id: "solana/guides/create-feed" },
    { type: "ref", id: "solana/guides/priority-fees" },
    { type: "ref", id: "solana/guides/vrf" },
    { type: "ref", id: "solana/guides/test-integration" },
  ],

  // archSidebar: [{ type: "autogenerated", dirName: "arch" }],
  // cliSidebar: [{ type: "autogenerated", dirName: "cli" }],

  aptosSidebar: [{ type: "autogenerated", dirName: "aptos" }],
  coreDaoSidebar: [{ type: "autogenerated", dirName: "coredao" }],
  nearSidebar: [{ type: "autogenerated", dirName: "near" }],
  solanaSidebar: [{ type: "autogenerated", dirName: "solana" }],
  starknetSidebar: [{ type: "autogenerated", dirName: "starknet" }],
  suiSidebar: [{ type: "autogenerated", dirName: "sui" }],
};

module.exports = sidebars;
