// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  gettingStartedSidebar: [
    {
      type: "html",
      value: '<div class="sidebar__heading-label">About</div>',
    },
    { type: "doc", id: "about", className: "tight-sidebar" },
    { type: "doc", id: "network", className: "tight-sidebar" },
    { type: "doc", id: "data-models", className: "tight-sidebar" },
    { type: "doc", id: "oracle-program", className: "tight-sidebar" },
    { type: "doc", id: "attestation-program", className: "tight-sidebar" },
    { type: "doc", id: "what-can-i-build", className: "tight-sidebar" },
    { type: "html", value: '<hr class="sidebar-separator">' },
    {
      type: "html",
      value: '<div class="sidebar__heading-label">Products</div>',
    },
    { type: "doc", id: "functions", className: "tight-sidebar" },
    { type: "doc", id: "secrets", className: "tight-sidebar" },
    { type: "doc", id: "data-feeds", className: "tight-sidebar" },
    { type: "doc", id: "randomness", className: "tight-sidebar" },
    { type: "html", value: '<hr class="sidebar-separator">' },
    {
      type: "html",
      value: '<div class="sidebar__heading-label">Integrate</div>',
    },
    { type: "doc", id: "guides/index", className: "tight-sidebar" },
    {
      type: "category",
      collapsed: true,
      collapsible: true,
      label: "General Guides",
      items: [
        { type: "autogenerated", dirName: "guides/feeds" },
        { type: "autogenerated", dirName: "guides/infra" },
      ],
    },
    { type: "html", value: '<hr class="sidebar-separator">' },
    {
      type: "category",
      collapsed: true,
      collapsible: true,
      label: "Solana",
      link: {
        type: "doc",
        id: "solana/index",
      },
      items: [{ type: "autogenerated", dirName: "solana" }],
    },
    {
      type: "category",
      collapsed: true,
      collapsible: true,
      label: "EVM",
      link: {
        type: "doc",
        id: "evm/index",
      },
      items: [{ type: "autogenerated", dirName: "evm" }],
    },
    {
      type: "category",
      collapsed: true,
      collapsible: true,
      label: "Aptos",
      link: {
        type: "doc",
        id: "aptos/index",
      },
      items: [{ type: "autogenerated", dirName: "aptos" }],
    },
    {
      type: "category",
      collapsed: true,
      collapsible: true,
      label: "NEAR",
      link: {
        type: "doc",
        id: "near/index",
      },
      items: [{ type: "autogenerated", dirName: "near" }],
    },
    {
      type: "category",
      collapsed: true,
      collapsible: true,
      label: "Sui",
      link: {
        type: "doc",
        id: "sui/index",
      },
      items: [{ type: "autogenerated", dirName: "sui" }],
    },
  ],
};

module.exports = sidebars;
