// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  gettingStartedSidebar: [
    "about",
    "oracles",
    "terminology",
    // { type: "html", value: '<hr class="sidebar-separator">' },
    // {
    //   type: "html",
    //   value:
    //     '<h3 class="sidebar__custom_label sidebar__category_label">Products</h3>',
    // },
    // {
    //   type: "category",
    //   label: "Products",
    //   link: {
    //     type: "doc",
    //     id: "products",
    //   },
    //   collapsible: false,
    //   items: [{ type: "autogenerated", dirName: "products" }],
    // },
    { type: "html", value: '<hr class="sidebar-separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">Architecture</h3>',
    },
    { type: "autogenerated", dirName: "arch" },
  ],

  guidesSidebar: [
    "guides",
    { type: "html", value: '<hr class="sidebar-separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">General</h3>',
    },
    { type: "autogenerated", dirName: "guides/feeds" },
    { type: "autogenerated", dirName: "guides/oracles" },
    { type: "html", value: '<hr class="sidebar-separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">Solana</h3>',
    },
    { type: "ref", id: "solana/guides/feeds", className: "sidebar__external" },
    {
      type: "ref",
      id: "solana/guides/priority-fees",
      className: "sidebar__external",
    },
    { type: "ref", id: "solana/guides/vrf", className: "sidebar__external" },
    {
      type: "ref",
      id: "solana/guides/test-integration",
      className: "sidebar__external",
    },
  ],

  aptosSidebar: [
    { type: "doc", id: "aptos/index", className: "sidebar__aptos" },
    { type: "autogenerated", dirName: "aptos/sdk" },
    { type: "html", value: '<hr class="sidebar-separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">Guides</h3>',
    },
    { type: "autogenerated", dirName: "aptos/guides" },
  ],

  coreDaoSidebar: [
    { type: "doc", id: "coredao/index", className: "sidebar__coredao" },
    { type: "autogenerated", dirName: "coredao/sdk" },
    { type: "html", value: '<hr class="sidebar-separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">Guides</h3>',
    },
    { type: "autogenerated", dirName: "coredao/guides" },
  ],
  nearSidebar: [
    { type: "doc", id: "near/index", className: "sidebar__near" },
    { type: "autogenerated", dirName: "near/sdk" },
    { type: "html", value: '<hr class="sidebar-separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">Guides</h3>',
    },
    { type: "autogenerated", dirName: "near/guides" },
  ],
  solanaSidebar: [
    { type: "doc", id: "solana/index", className: "sidebar__solana" },
    { type: "autogenerated", dirName: "solana/sdk" },
    { type: "html", value: '<hr class="sidebar-separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">Guides</h3>',
    },
    { type: "autogenerated", dirName: "solana/guides" },
  ],
  suiSidebar: [
    { type: "doc", id: "sui/index", className: "sidebar__sui" },
    { type: "autogenerated", dirName: "sui/sdk" },
    { type: "html", value: '<hr class="sidebar-separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">Guides</h3>',
    },
    { type: "autogenerated", dirName: "sui/guides" },
  ],
};

module.exports = sidebars;
