module.exports = {
  publisher: [
    {
      type: "doc",
      id: "publisher/overview",
      label: "📚 Publisher",
    },
    {
      type: "doc",
      id: "publisher/connect-wallet",
    },
    {
      type: "doc",
      id: "publisher/my-feeds",
    },
    {
      type: "doc",
      id: "publisher/create-feed",
    },
    {
      type: "category",
      label: "Task Definitions",
      collapsible: false,
      items: [
        { type: "doc", id: "tasks/OracleJob" },
        {
          type: "category",
          label: "Tasks",
          items: [
            { type: "doc", id: "tasks/AddTask" },
            { type: "doc", id: "tasks/AnchorFetchTask" },
            { type: "doc", id: "tasks/BoundTask" },
            { type: "doc", id: "tasks/BufferLayoutParseTask" },
            { type: "doc", id: "tasks/CacheTask" },
            { type: "doc", id: "tasks/ComparisonTask" },
            { type: "doc", id: "tasks/ConditionalTask" },
            { type: "doc", id: "tasks/CronParseTask" },
            { type: "doc", id: "tasks/DefiKingdomsTask" },
            { type: "doc", id: "tasks/DivideTask" },
            { type: "doc", id: "tasks/EwmaTask" },
            { type: "doc", id: "tasks/HistoryFunctionTask" },
            { type: "doc", id: "tasks/HttpTask" },
            { type: "doc", id: "tasks/JsonParseTask" },
            { type: "doc", id: "tasks/JupiterSwapTask" },
            { type: "doc", id: "tasks/LendingRateTask" },
            { type: "doc", id: "tasks/LpExchangeRateTask" },
            { type: "doc", id: "tasks/LpTokenPriceTask" },
            { type: "doc", id: "tasks/MangoPerpMarketTask" },
            { type: "doc", id: "tasks/MarinadeStateTask" },
            { type: "doc", id: "tasks/MaxTask" },
            { type: "doc", id: "tasks/MeanTask" },
            { type: "doc", id: "tasks/MedianTask" },
            { type: "doc", id: "tasks/MinTask" },
            { type: "doc", id: "tasks/MultiplyTask" },
            { type: "doc", id: "tasks/OracleTask" },
            { type: "doc", id: "tasks/PancakeswapExchangeRateTask" },
            { type: "doc", id: "tasks/PerpMarketTask" },
            { type: "doc", id: "tasks/PowTask" },
            { type: "doc", id: "tasks/RegexExtractTask" },
            { type: "doc", id: "tasks/RoundTask" },
            { type: "doc", id: "tasks/SerumSwapTask" },
            { type: "doc", id: "tasks/SolanaAccountDataFetchTask" },
            { type: "doc", id: "tasks/SplStakePoolTask" },
            { type: "doc", id: "tasks/SplTokenParseTask" },
            { type: "doc", id: "tasks/SubtractTask" },
            { type: "doc", id: "tasks/SushiswapExchangeRateTask" },
            { type: "doc", id: "tasks/SysclockOffsetTask" },
            { type: "doc", id: "tasks/TpsTask" },
            { type: "doc", id: "tasks/TwapTask" },
            { type: "doc", id: "tasks/UniswapExchangeRateTask" },
            { type: "doc", id: "tasks/ValueTask" },
            { type: "doc", id: "tasks/VwapTask" },
            { type: "doc", id: "tasks/WebsocketTask" },
            { type: "doc", id: "tasks/XStepPriceTask" },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Examples",
      collapsible: false,
      items: [{ type: "autogenerated", dirName: "publisher/examples" }],
    },
  ],

  about: [
    { type: "autogenerated", dirName: "about" },
    { type: "html", value: '<hr class="sidebar-separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">Quick Links</h3>',
    },
    {
      type: "link",
      label: "📐 Learn",
      href: "/network",
    },
    {
      type: "link",
      label: "🚀 Switchboard V3",
      href: "/v3",
    },
    {
      type: "link",
      label: "Github",
      href: "https://github.com/switchboard-xyz",
      className: "sidebar__github",
    },
    {
      type: "link",
      label: "🔎 Explorer",
      href: "https://switchboard.xyz/explorer",
    },
    {
      type: "link",
      label: "📚 Publisher",
      href: "https://app.switchboard.xyz/",
    },
    { type: "html", value: '<hr class="sidebar-separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">Integrate</h3>',
    },
    {
      type: "link",
      label: "Aptos",
      className: "sidebar__aptos",
      href: "/aptos",
    },
    {
      type: "link",
      label: "CoreDAO",
      className: "sidebar__coredao",
      href: "/coredao",
    },
    {
      type: "link",
      label: "Near",
      className: "sidebar__near",
      href: "/near",
    },
    {
      type: "link",
      label: "Solana",
      className: "sidebar__solana",
      href: "/solana",
    },
    {
      type: "link",
      label: "StarkNet",
      className: "sidebar__starknet",
      href: "/starknet",
    },
    {
      type: "link",
      label: "Sui",
      className: "sidebar__sui",
      href: "/sui",
    },
  ],

  v3: [
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">Switchboard V3</h3>',
    },
    { type: "autogenerated", dirName: "v3" },
  ],

  learn: [
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">Network</h3>',
    },
    { type: "autogenerated", dirName: "network" },
    { type: "html", value: '<hr class="sidebar-separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">Feeds</h3>',
    },
    { type: "autogenerated", dirName: "feeds" },
    { type: "html", value: '<hr class="sidebar-separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">Randomness</h3>',
    },
    { type: "autogenerated", dirName: "randomness" },
  ],

  operator: [
    {
      type: "doc",
      label: "Switchboard Operator",
      className: "sidebar__oracle",
      id: "operator/overview",
    },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">Network</h3>',
    },
    { type: "autogenerated", dirName: "operator/queue" },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">Oracle</h2>',
    },
    { type: "autogenerated", dirName: "operator/oracle" },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">Crank</h2>',
    },
    { type: "autogenerated", dirName: "operator/crank" },
  ],

  aptos: [
    {
      type: "doc",
      label: "Aptos",
      className: "sidebar__aptos",
      id: "aptos/overview",
    },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">Program</h3>',
    },
    { type: "autogenerated", dirName: "aptos/program" },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">SDK</h2>',
    },
    { type: "doc", id: "aptos/dev/overview" },
    { type: "doc", id: "aptos/dev/cli", className: "sidebar__terminal" },
    {
      type: "doc",
      id: "aptos/dev/move",
      label: "sbv2-aptos",
      className: "sidebar__rust",
    },
    {
      type: "doc",
      id: "aptos/dev/javascript",
      label: "@switchboard-xyz/aptos.js",
      className: "sidebar__typescript",
    },
    {
      type: "doc",
      id: "aptos/dev/feed-parser",
      label: "Feed Parser Example",
      className: "sidebar__rust",
    },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">IDL</h2>',
    },
    { type: "autogenerated", dirName: "aptos/idl" },
  ],

  coredao: [
    {
      type: "doc",
      label: "CoreDAO",
      className: "sidebar__coredao",
      id: "coredao/overview",
    },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">Program</h3>',
    },
    { type: "autogenerated", dirName: "coredao/program" },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">SDK</h2>',
    },
    { type: "doc", id: "coredao/dev/overview" },
    {
      type: "doc",
      id: "coredao/dev/javascript",
      label: "@switchboard-xyz/evm.js",
      className: "sidebar__typescript",
    },
    {
      type: "doc",
      id: "coredao/dev/solidity/ISwitchboard",
      label: "ISwitchboard.sol",
      className: "sidebar__solidity",
    },
    {
      type: "doc",
      id: "coredao/dev/solidity/ILegacyOracle",
      label: "ILegacyOracle.sol",
      className: "sidebar__solidity",
    },
    {
      type: "doc",
      id: "coredao/dev/read-feed",
      label: "Read Feed Example",
      className: "sidebar__solidity",
    },
  ],

  near: [
    {
      type: "doc",
      label: "Near",
      className: "sidebar__near",
      id: "near/overview",
    },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">Program</h3>',
    },
    { type: "autogenerated", dirName: "near/program" },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">SDK</h2>',
    },
    { type: "doc", id: "near/dev/overview" },
    { type: "doc", id: "near/dev/cli", className: "sidebar__terminal" },
    {
      type: "doc",
      id: "near/dev/rust",
      label: "sbv2-near",
      className: "sidebar__rust",
    },
    {
      type: "doc",
      id: "near/dev/javascript",
      label: "@switchboard-xyz/near.js",
      className: "sidebar__typescript",
    },
    {
      type: "doc",
      id: "near/dev/feed-parser",
      label: "Feed Parser Example",
      className: "sidebar__rust",
    },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">IDL</h2>',
    },
    { type: "autogenerated", dirName: "near/idl" },
  ],

  solana: [
    {
      type: "doc",
      label: "Solana",
      className: "sidebar__solana",
      id: "solana/overview",
    },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">Program</h3>',
    },
    { type: "autogenerated", dirName: "solana/program" },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">Guides</h3>',
    },
    { type: "doc", id: "solana/feed-integration" },
    { type: "doc", id: "solana/priority-fees" },
    { type: "doc", id: "solana/vrf-integration" },
    { type: "doc", id: "solana/test-integration" },
    // { type: "doc", id: "solana/advanced-walkthrough" },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">SDK</h2>',
    },
    { type: "doc", id: "solana/dev/overview" },
    { type: "doc", id: "solana/dev/cli", className: "sidebar__terminal" },
    {
      type: "doc",
      id: "solana/dev/rust",
      label: "switchboard-v2",
      className: "sidebar__rust",
    },
    {
      type: "doc",
      id: "solana/dev/javascript",
      label: "@switchboard-xyz/solana.js",
      className: "sidebar__typescript",
    },
    {
      type: "doc",
      id: "solana/dev/python",
      label: "switchboardpy",
      className: "sidebar__python",
    },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">IDL</h2>',
    },
    { type: "autogenerated", dirName: "solana/idl" },
  ],

  starknet: [
    {
      type: "doc",
      label: "StarkNet",
      className: "sidebar__starknet",
      id: "starknet/overview",
    },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">Program</h3>',
    },
    { type: "autogenerated", dirName: "starknet/program" },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">SDK</h2>',
    },
    { type: "autogenerated", dirName: "starknet/dev" },
  ],

  sui: [
    {
      type: "doc",
      label: "Sui",
      className: "sidebar__sui",
      id: "sui/overview",
    },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">Program</h3>',
    },
    { type: "autogenerated", dirName: "sui/program" },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">SDK</h2>',
    },
    { type: "autogenerated", dirName: "sui/dev" },
  ],

  dev: [
    {
      type: "doc",
      id: "dev/overview",
      label: "🛠️ Developer Resources",
      className: "sidebar__custom_doc_label",
    },
    {
      type: "doc",
      id: "dev/common",
      label: "@switchboard-xyz/common",
    },
    {
      type: "doc",
      id: "dev/oracle",
      label: "@switchboard-xyz/oracle",
    },
    {
      type: "category",
      label: "@switchboard-xyz/cli",
      collapsible: false,
      items: [{ type: "autogenerated", dirName: "dev/cli" }],
    },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "link",
      href: "/solana/dev",
      label: "Solana Resources",
      className: "sidebar__solana sidebar__custom_doc_label",
    },
    {
      type: "link",
      href: "/solana/dev/rust",
      label: "switchboard-v2",
      className: "sidebar__rust",
    },
    {
      type: "link",
      href: "/solana/dev/javascript",
      label: "@switchboard-xyz/solana.js",
      className: "sidebar__typescript",
    },
    {
      type: "link",
      href: "/solana/dev/python",
      label: "switchboardpy",
      className: "sidebar__python",
    },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "link",
      href: "/aptos/dev",
      label: "Aptos Resources",
      className: "sidebar__aptos sidebar__custom_doc_label",
    },
    {
      type: "link",
      href: "/aptos/dev/move",
      label: "switchboard",
      className: "sidebar__rust",
    },
    {
      type: "link",
      href: "/aptos/dev/javascript",
      label: "@switchboard-xyz/aptos.js",
      className: "sidebar__typescript",
    },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "link",
      href: "/coredao/dev",
      label: "CoreDAO Resources",
      className: "sidebar__coredao sidebar__custom_doc_label",
    },
    {
      type: "link",
      href: "/coredao/dev/javascript",
      label: "@switchboard-xyz/evm.js",

      className: "sidebar__typescript",
    },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "link",
      href: "/near/dev",
      label: "Near Resources",
      className: "sidebar__near sidebar__custom_doc_label",
    },
    {
      type: "link",
      href: "/near/dev/rust",
      label: "sbv2-near",
      className: "sidebar__rust",
    },
    {
      type: "link",
      href: "/near/dev/javascript",
      label: "@switchboard-xyz/near.js",

      className: "sidebar__typescript",
    },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "link",
      href: "/starknet/dev",
      label: "Starknet Resources",
      className: "sidebar__starknet sidebar__custom_doc_label",
    },
    {
      type: "link",
      href: "/starknet/dev/javascript",
      label: "@switchboard-xyz/starknet.js",
      className: "sidebar__typescript",
    },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "link",
      href: "/sui/dev",
      label: "Sui Resources",
      className: "sidebar__sui sidebar__custom_doc_label",
    },
    {
      type: "link",
      href: "/sui/dev/javascript",
      label: "@switchboard-xyz/sui.js",
      className: "sidebar__typescript",
    },
    // { type: "html", value: '<hr class="sidebar__separator">' },
    // {
    //   type: "link",
    //   href: "/solana/dev",
    //   label: "Solana Resources",
    //   className: "sidebar__solana sidebar__custom_doc_label",
    // },
    // {
    //   type: "link",
    //   label: "@switchboard-xyz/switchboard-v2",
    //   className: "sidebar__typescript",
    //   href: "https://switchboard-xyz.github.io/sbv2-core/api/@switchboard-xyz/switchboard-v2",
    // },
    // {
    //   type: "link",
    //   label: "@switchboard-xyz/sbv2-lite",
    //   className: "sidebar__typescript",
    //   href: "https://switchboard-xyz.github.io/sbv2-core/api/@switchboard-xyz/sbv2-lite",
    // },
    // {
    //   type: "link",
    //   label: "switchboardpy",
    //   className: "sidebar__python",
    //   href: "https://switchboard-xyz.github.io/sbv2-core/api/switchboardpy",
    // },
    // {
    //   type: "link",
    //   label: "switchboard-v2",
    //   className: "sidebar__rust",
    //   href: "https://docs.rs/switchboard-v2/latest/switchboard_v2/",
    // },
  ],
};
