module.exports = {
  publisher: [
    {
      type: "doc",
      id: "publisher/overview",
    },

    {
      type: "category",
      label: "Protos",
      collapsible: false,
      items: [
        { type: "doc", id: "protos/OracleJob" },
        {
          type: "category",
          label: "Tasks",
          items: [
            { type: "doc", id: "protos/AddTask" },
            { type: "doc", id: "protos/AnchorFetchTask" },
            { type: "doc", id: "protos/BoundTask" },
            { type: "doc", id: "protos/BufferLayoutParseTask" },
            { type: "doc", id: "protos/CacheTask" },
            { type: "doc", id: "protos/ComparisonTask" },
            { type: "doc", id: "protos/ConditionalTask" },
            { type: "doc", id: "protos/CronParseTask" },
            { type: "doc", id: "protos/DefiKingdomsTask" },
            { type: "doc", id: "protos/DivideTask" },
            { type: "doc", id: "protos/EwmaTask" },
            { type: "doc", id: "protos/HistoryFunctionTask" },
            { type: "doc", id: "protos/HttpTask" },
            { type: "doc", id: "protos/JsonParseTask" },
            { type: "doc", id: "protos/JupiterSwapTask" },
            { type: "doc", id: "protos/LendingRateTask" },
            { type: "doc", id: "protos/LpExchangeRateTask" },
            { type: "doc", id: "protos/LpTokenPriceTask" },
            { type: "doc", id: "protos/MangoPerpMarketTask" },
            { type: "doc", id: "protos/MarinadeStateTask" },
            { type: "doc", id: "protos/MaxTask" },
            { type: "doc", id: "protos/MeanTask" },
            { type: "doc", id: "protos/MedianTask" },
            { type: "doc", id: "protos/MinTask" },
            { type: "doc", id: "protos/MultiplyTask" },
            { type: "doc", id: "protos/OracleTask" },
            { type: "doc", id: "protos/PancakeswapExchangeRateTask" },
            { type: "doc", id: "protos/PerpMarketTask" },
            { type: "doc", id: "protos/PowTask" },
            { type: "doc", id: "protos/RegexExtractTask" },
            { type: "doc", id: "protos/RoundTask" },
            { type: "doc", id: "protos/SerumSwapTask" },
            { type: "doc", id: "protos/SolanaAccountDataFetchTask" },
            { type: "doc", id: "protos/SplStakePoolTask" },
            { type: "doc", id: "protos/SplTokenParseTask" },
            { type: "doc", id: "protos/SubtractTask" },
            { type: "doc", id: "protos/SushiswapExchangeRateTask" },
            { type: "doc", id: "protos/SysclockOffsetTask" },
            { type: "doc", id: "protos/TpsTask" },
            { type: "doc", id: "protos/TwapTask" },
            { type: "doc", id: "protos/UniswapExchangeRateTask" },
            { type: "doc", id: "protos/ValueTask" },
            { type: "doc", id: "protos/VwapTask" },
            { type: "doc", id: "protos/WebsocketTask" },
            { type: "doc", id: "protos/XStepPriceTask" },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Examples",
      collapsible: false,
      items: [{ type: "autogenerated", dirName: "publisher/examples" }],
    },
  ],

  about: [
    { type: "autogenerated", dirName: "about" },
    { type: "html", value: '<hr class="sidebar-separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">Quick Links</h3>',
    },
    {
      type: "link",
      label: "📐 Learn",
      href: "/network",
    },
    {
      type: "link",
      label: "Github",
      href: "https://github.com/switchboard-xyz",
      className: "sidebar__github",
    },
    {
      type: "link",
      label: "🔎 Explorer",
      href: "https://switchboard.xyz/explorer",
    },
    {
      type: "link",
      label: "📚 Publisher",
      href: "https://app.switchboard.xyz/",
    },
    { type: "html", value: '<hr class="sidebar-separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">Integrate</h3>',
    },
    {
      type: "link",
      label: "Aptos",
      className: "sidebar__aptos",
      href: "/aptos",
    },
    {
      type: "link",
      label: "CoreDAO",
      className: "sidebar__coredao",
      href: "/coredao",
    },
    {
      type: "link",
      label: "Near",
      className: "sidebar__near",
      href: "/near",
    },
    {
      type: "link",
      label: "Solana",
      className: "sidebar__solana",
      href: "/solana",
    },
    {
      type: "link",
      label: "StarkNet",
      className: "sidebar__starknet",
      href: "/starknet",
    },
    {
      type: "link",
      label: "Sui",
      className: "sidebar__sui",
      href: "/sui",
    },
  ],

  learn: [
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">Network</h3>',
    },
    { type: "autogenerated", dirName: "network" },
    { type: "html", value: '<hr class="sidebar-separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">Feeds</h3>',
    },
    { type: "autogenerated", dirName: "feeds" },
    { type: "html", value: '<hr class="sidebar-separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">Randomness</h3>',
    },
    { type: "autogenerated", dirName: "randomness" },
  ],

  operator: [
    {
      type: "doc",
      label: "Switchboard Operator",
      className: "sidebar__oracle",
      id: "operator/overview",
    },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">Network</h3>',
    },
    { type: "autogenerated", dirName: "operator/queue" },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">Oracle</h2>',
    },
    { type: "autogenerated", dirName: "operator/oracle" },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">Crank</h2>',
    },
    { type: "autogenerated", dirName: "operator/crank" },
  ],

  aptos: [
    {
      type: "doc",
      label: "Aptos",
      className: "sidebar__aptos",
      id: "aptos/overview",
    },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">Program</h3>',
    },
    { type: "autogenerated", dirName: "aptos/program" },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">SDK</h2>',
    },
    { type: "autogenerated", dirName: "aptos/dev" },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">IDL</h2>',
    },
    { type: "autogenerated", dirName: "aptos/idl" },
  ],

  coredao: [
    {
      type: "doc",
      label: "CoreDAO",
      className: "sidebar__coredao",
      id: "coredao/overview",
    },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">Program</h3>',
    },
    { type: "autogenerated", dirName: "coredao/program" },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">SDK</h2>',
    },
    { type: "autogenerated", dirName: "coredao/dev" },
  ],

  near: [
    {
      type: "doc",
      label: "Near",
      className: "sidebar__near",
      id: "near/overview",
    },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">Program</h3>',
    },
    { type: "autogenerated", dirName: "near/program" },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">SDK</h2>',
    },
    { type: "autogenerated", dirName: "near/dev" },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">IDL</h2>',
    },
    { type: "autogenerated", dirName: "near/idl" },
  ],

  solana: [
    {
      type: "doc",
      label: "Solana",
      className: "sidebar__solana",
      id: "solana/overview",
    },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">Program</h3>',
    },
    { type: "autogenerated", dirName: "solana/program" },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">Misc</h2>',
    },
    { type: "doc", id: "solana/priority-fees" },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">SDK</h2>',
    },
    { type: "autogenerated", dirName: "solana/dev" },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">IDL</h2>',
    },
    { type: "autogenerated", dirName: "solana/idl" },
  ],

  starknet: [
    {
      type: "doc",
      label: "StarkNet",
      className: "sidebar__starknet",
      id: "starknet/overview",
    },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">Program</h3>',
    },
    { type: "autogenerated", dirName: "starknet/program" },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">SDK</h2>',
    },
    { type: "autogenerated", dirName: "starknet/dev" },
  ],

  sui: [
    {
      type: "doc",
      label: "Sui",
      className: "sidebar__sui",
      id: "sui/overview",
    },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">Program</h3>',
    },
    { type: "autogenerated", dirName: "sui/program" },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "html",
      value:
        '<h3 class="sidebar__custom_label sidebar__category_label">SDK</h2>',
    },
    { type: "autogenerated", dirName: "sui/dev" },
  ],

  dev: [
    {
      type: "doc",
      id: "dev/overview",
      label: "🛠️ Developer Resources",
      className: "sidebar__custom_doc_label",
    },
    {
      type: "doc",
      id: "dev/common",
      label: "@switchboard-xyz/common",
    },
    {
      type: "category",
      label: "@switchboard-xyz/cli",
      collapsible: false,
      items: [{ type: "autogenerated", dirName: "dev/cli" }],
    },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "link",
      href: "/aptos/dev",
      label: "Solana Resources",
      className: "sidebar__solana sidebar__custom_doc_label",
    },
    {
      type: "link",
      href: "/solana/dev/rust",
      label: "switchboard-v2",
      className: "sidebar__rust",
    },
    {
      type: "link",
      href: "/solana/dev/javascript",
      label: "@switchboard-xyz/solana.js",
      className: "sidebar__typescript",
    },
    {
      type: "link",
      href: "/solana/dev/python",
      label: "switchboardpy",
      className: "sidebar__python",
    },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "link",
      href: "/aptos/dev",
      label: "Aptos Resources",
      className: "sidebar__aptos sidebar__custom_doc_label",
    },
    {
      type: "link",
      href: "/aptos/dev/move",
      label: "switchboard",
      className: "sidebar__rust",
    },
    {
      type: "link",
      href: "/aptos/dev/javascript",
      label: "@switchboard-xyz/aptos.js",
      className: "sidebar__typescript",
    },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "link",
      href: "/coredao/dev",
      label: "CoreDAO Resources",
      className: "sidebar__coredao sidebar__custom_doc_label",
    },
    {
      type: "link",
      href: "/coredao/dev/javascript",
      label: "@switchboard-xyz/evm.js",

      className: "sidebar__typescript",
    },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "link",
      href: "/near/dev",
      label: "Near Resources",
      className: "sidebar__near sidebar__custom_doc_label",
    },
    {
      type: "link",
      href: "/near/dev/rust",
      label: "sbv2-near",
      className: "sidebar__rust",
    },
    {
      type: "link",
      href: "/near/dev/javascript",
      label: "@switchboard-xyz/near.js",

      className: "sidebar__typescript",
    },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "link",
      href: "/starknet/dev",
      label: "Starknet Resources",
      className: "sidebar__starknet sidebar__custom_doc_label",
    },
    {
      type: "link",
      href: "/starknet/dev/javascript",
      label: "@switchboard-xyz/starknet.js",
      className: "sidebar__typescript",
    },
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "link",
      href: "/sui/dev",
      label: "Sui Resources",
      className: "sidebar__sui sidebar__custom_doc_label",
    },
    {
      type: "link",
      href: "/sui/dev/javascript",
      label: "@switchboard-xyz/sui.js",
      className: "sidebar__typescript",
    },
    // { type: "html", value: '<hr class="sidebar__separator">' },
    // {
    //   type: "link",
    //   href: "/solana/dev",
    //   label: "Solana Resources",
    //   className: "sidebar__solana sidebar__custom_doc_label",
    // },
    // {
    //   type: "link",
    //   label: "@switchboard-xyz/switchboard-v2",
    //   className: "sidebar__typescript",
    //   href: "https://switchboard-xyz.github.io/sbv2-core/api/@switchboard-xyz/switchboard-v2",
    // },
    // {
    //   type: "link",
    //   label: "@switchboard-xyz/sbv2-lite",
    //   className: "sidebar__typescript",
    //   href: "https://switchboard-xyz.github.io/sbv2-core/api/@switchboard-xyz/sbv2-lite",
    // },
    // {
    //   type: "link",
    //   label: "switchboardpy",
    //   className: "sidebar__python",
    //   href: "https://switchboard-xyz.github.io/sbv2-core/api/switchboardpy",
    // },
    // {
    //   type: "link",
    //   label: "switchboard-v2",
    //   className: "sidebar__rust",
    //   href: "https://docs.rs/switchboard-v2/latest/switchboard_v2/",
    // },
  ],
};
