module.exports = {
  gettingStarted: [
    "about/introduction",
    "about/architecture",
    "about/faq",
    "about/security",
  ],

  // aptos
  aptosFeeds: ["aptos/feeds/introduction"],

  // near
  nearFeeds: ["near/feeds/introduction"],

  // solana
  solanaFeeds: [
    "solana/feeds/introduction",
    "solana/feeds/create",
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "category",
      label: "IDL",
      collapsible: false,
      items: [{ type: "autogenerated", dirName: "solana/idl" }],
    },
  ],
  solanaRandomness: [
    "solana/randomness/architecture",
    "solana/randomness/integration",
    { type: "html", value: '<hr class="sidebar__separator">' },
    {
      type: "doc",
      id: "solana/idl/accounts/VrfAccountData",
      label: "VRF Account Data",
    },
    // { type: "html", value: '<hr class="sidebar-separator">' },
    // {
    //   type: "category",
    //   label: "IDL",
    //   collapsible: false,
    //   items: [{ type: "autogenerated", dirName: "solana/idl" }],
    // },
  ],
  // solanaIdl: [{ type: "autogenerated", dirName: "solana/idl" }],

  // Oracle Operator
  oracle: [
    "oracle/background",
    "oracle/configuration",
    "oracle/docker",
    "oracle/gcp",
    "oracle/monitoring",
  ],

  // Switchboard Feeds
  feeds: [
    "feeds/introduction",
    "feeds/best-practices",
    "feeds/tasks",
    { type: "html", value: '<hr class="sidebar-separator">' },
    {
      type: "category",
      label: "Publisher",
      collapsible: false,
      items: [{ type: "autogenerated", dirName: "feeds/publisher" }],
    },
    { type: "html", value: '<hr class="sidebar-separator">' },
    {
      type: "category",
      label: "Examples",
      collapsible: false,
      className: "sidebar__custom_label",
      items: [{ type: "autogenerated", dirName: "feeds/examples" }],
    },
  ],

  api: [
    { type: "doc", id: "api/overview", label: "🛠️ Developer Resources" },
    {
      type: "link",
      label: "@switchboard-xyz/common",
      className: "sidebar__typescript",
      href: "https://switchboard-xyz.github.io/sbv2-core/api/@switchboard-xyz/common",
    },
    {
      type: "category",
      label: "@switchboard-xyz/cli",
      collapsible: true,
      items: [{ type: "autogenerated", dirName: "api/cli" }],
    },
    { type: "html", value: '<hr class="sidebar__double-separator">' },
    {
      type: "doc",
      id: "api/aptos",
      className: "sidebar__aptos",
    },
    {
      type: "link",
      label: "@switchboard-xyz/aptos.js",
      className: "sidebar__typescript",
      href: "https://switchboard-xyz.github.io/sbv2-core/api/@switchboard-xyz/aptos.js",
    },
    { type: "html", value: '<hr class="sidebar__double-separator">' },
    {
      type: "doc",
      id: "api/near",
      className: "sidebar__near",
    },
    {
      type: "link",
      label: "@switchboard-xyz/near.js",
      className: "sidebar__typescript",
      href: "https://switchboard-xyz.github.io/sbv2-core/api/@switchboard-xyz/near.js",
    },
    { type: "html", value: '<hr class="sidebar__double-separator">' },
    {
      type: "doc",
      id: "api/solana",
      className: "sidebar__solana",
    },
    {
      type: "link",
      label: "@switchboard-xyz/solana.js",
      className: "sidebar__typescript",
      href: "https://switchboard-xyz.github.io/sbv2-core/api/@switchboard-xyz/solana.js",
    },
    {
      type: "link",
      label: "@switchboard-xyz/sbv2-lite",
      className: "sidebar__typescript",
      href: "https://switchboard-xyz.github.io/sbv2-core/api/@switchboard-xyz/sbv2-lite",
    },
    {
      type: "link",
      label: "switchboardpy",
      className: "sidebar__python",
      href: "https://switchboard-xyz.github.io/sbv2-core/api/switchboardpy",
    },
    {
      type: "link",
      label: "switchboard-v2",
      className: "sidebar__rust",
      href: "https://docs.rs/switchboard-v2/latest/switchboard_v2/",
    },
  ],
};
